### ISSUE TITLE
reia fails to load ?sometimes? : os x 10.4.11

### ISSUE THREAD

**Issue by pirj** [tarcieri/reia#1]
reia apps fail to load sometimes (os x 10.4.11) for unknown reason
(maybe an erlang issue)

pirj-2:~/source/tarcieri-reia philpirj$ ire
/usr/local/bin/ire: line 3:  2116 Bus error               erl +K true -pa ebin -pa ../ebin -noshell -noinput -s ire init -extra $*
pirj-2:~/source/tarcieri-reia philpirj$ ire
Reia Interactive Shell (prerelease)

**Comment by tarcieri** [comment]
Wow... I'm on OS X 10.5.6 here w\ Erlang R12B-5.  I have not experienced a bus error.

**Comment by pirj** [comment]
erlang r12b-5 too

this appeared after my not-very-succesful clone of Rakefile, you have seen the difference in /usr/local/bin/reia of course, it runs but have this issue

it might be better to have /bin/reia_global to be copied to /usr/local/bin, not /bin/reia that's handy to be used during reia devellopment (same for ire)

i might be dumb, but i haven't found the way to pass the # and $ symbols to a file from makefile correctly without $\* variable being resolved and # be treated as comment (even if i did '#' + '..other contents' and '$' + 'other contents')
