### ISSUE TITLE
can't split list comprehension clauses

### ISSUE THREAD

**Issue by jacaetevha** [tarcieri/reia#12]
I have some code at http://pastie.org/1268287 . I wanted to split up the list comprehension into multiple lines but the parser fails to parse it (see http://pastie.org/1268322). Am I doing something wrong?

**Comment by tarcieri** [comment]
Nope, not your fault, there are a lot of issues parsing constructions where newlines should be optional. Some work was being done on the neotoma-based PEG grammar to fix this issue more generically. For now I have to add optional newlines on a case-by-case basis.

**Comment by jacaetevha** [comment]
Thanks. I really like the project! I wish I could be of help to you, but a lot of the nitty-gritty is over my head.
