### ISSUE TITLE
Lazy evaluation?

### ISSUE THREAD

**Issue by masylum** [tarcieri/reia#18]
Reia looks amazing!
Looks like a dreamed bastard son of Ruby, Erlang and Javascript.

Will it provide lazy evaluation on infinite ranges?

[n for n in 1.., n % 2 == 0].take(5)
=> [2, 4, 6, 8, 10]

That would be amazing!

**Comment by tarcieri** [comment]
It might be possible... it's not a feature you're likely to see soon though
