### ISSUE TITLE
class method call crashes when there's a method with the same name but different number of args

### ISSUE THREAD

**Issue by pirj** [tarcieri/reia#6]
class Controller
  def render(filename)
    ~a

  def render(filename, bindings)
    ~html

> > load('issue.re')
> > => Controller
> > Controller().render(~a)
> > => ~a
> > Controller().render(~a, ~b)
> > **\* ERROR: Shell process terminated! (^G to start new job) ***

=ERROR REPORT==== 28-Feb-2009::18:08:09 ===
                                           *\* Generic server <0.56.0> terminating 
                                                                                  *\* Last message in was {render,[a,b]}
                                                                                                                       *\* When Server state == {dict,0,16,16,8,80,48,
                                                        {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                                                                                                                     []},
                                                                                                                                                                       {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                                                                                           []}}}
                                                                                                                *\* Reason for termination == 
  *\* {function_clause,[{'Controller','__re_method_render',3},
                                                                                  {'Controller',handle_call,3},
                                                                                                                                    {reia_dispatch,funcall,3}]}

**Comment by tarcieri** [comment]
Hmm, Github Flavored Markdown did a number on that.  That said, this appears to be rather old (still using the "spurtee" atom sigil and all).  I just tried it out and it seems to be working fine.  Reopen if that's not the case.
