### ISSUE TITLE
shift: 4: can't shift that many

### ISSUE THREAD

**Issue by jdp** [tarcieri/reia#7]
I cloned a brand new reia repo, did `make` and then `sudo make install` (I had to manually create `/usr/local/lib/erlang` and `/usr/local/lib/erlang/lib` before it would work though, a mkdir call was failing). I finally got it installed, but whenever I run reia, I see this:

```
shift: 4: can't shift that many
```

What is that error?

**Comment by tarcieri** [comment]
Sounds like it might be a problem with the Makefile.  Can you try building Reia with rake instead and see if that fixes the problem?

**Comment by miebach** [comment]
jdp, try running "ire" instead of "reia"

**Comment by rdtft** [comment]
There was a similar problem (ArchLinux, shell = zsh)
Decided it so:
in Rakefile
http://gist.github.com/254545
